"""
Harvester for Vocabulary Decks from Direct Hits and SAT Power Vocab.
Creates:
1. data/flashcards/vocabulary_direct_hits.json (50 high-yield academic words)
2. data/flashcards/vocabulary_secondary_meanings.json (50 words with crucial secondary meanings)
"""
import json, os

out_dir = r'd:\antigravity_scratch\real_estate_scoring\sql\SAT\data\flashcards'

# 1. 50 High-Yield Core Words from Direct Hits
direct_hits_cards = [
  {
    "card_id": "FC-DH-001",
    "type": "vocabulary",
    "difficulty": 2,
    "front": {"word": "meticulous", "context": "The forensic botanist conducted a meticulous examination of the pollen samples, noting minute differences under the electron microscope."},
    "back": {"meaning": "Extremely careful and precise; showing great attention to detail", "synonyms": ["painstaking", "scrupulous", "exacting"], "contrast": "Not 'careless' or 'cursory'", "example": "Her meticulous notes allowed subsequent researchers to replicate the complex experiment perfectly."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-002",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "pragmatic", "context": "Rather than clinging to rigid economic dogma, the mayor adopted a pragmatic approach to municipal transit reform."},
    "back": {"meaning": "Dealing with things sensibly and realistically based on practical considerations rather than theoretical ideals", "synonyms": ["practical", "utilitarian", "expedient"], "contrast": "Not 'idealistic' or 'quixotic'", "example": "A pragmatic scientist tests hypotheses against observable evidence rather than preconceived assumptions."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-003",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "recalcitrant", "context": "The recalcitrant parliament refused to ratify the climate treaty without substantial exemptions for domestic industries."},
    "back": {"meaning": "Obstinately defiant of authority or guidance; stubbornly uncooperative", "synonyms": ["intractable", "refractory", "obstinate"], "contrast": "Not 'compliant' or 'amenable'", "example": "The recalcitrant bacteria showed resistance to all three primary classes of antibiotics."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-004",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "clandestine", "context": "Archaeologists uncovered evidence of clandestine trade routes used to smuggle obsidian across the classical Maya lowlands."},
    "back": {"meaning": "Kept secret or done secretively, especially because illicit", "synonyms": ["surreptitious", "covert", "furtive"], "contrast": "Not 'overt' or 'conspicuous'", "example": "The committee held clandestine meetings to avoid alerting the press before finalizing their findings."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-005",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "diffident", "context": "Although she was an expert mathematician, she remained diffident during faculty debates, rarely asserting her authority."},
    "back": {"meaning": "Modest or shy because of a lack of self-confidence", "synonyms": ["reticent", "timid", "unassertive"], "contrast": "Not 'arrogant' or 'presumptuous'", "example": "His diffident manner masked an extraordinarily sharp intellect."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-006",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "equanimity", "context": "The flight controller maintained complete equanimity throughout the navigational emergency, issuing calm instructions to the flight crew."},
    "back": {"meaning": "Mental calmness, composure, and evenness of temper, especially in a difficult situation", "synonyms": ["serenity", "sangfroid", "poise"], "contrast": "Not 'agitation' or 'hysteria'", "example": "Marcus Aurelius practiced Stoic exercises to cultivate inner equanimity amidst imperial turmoil."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-007",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "ephemeral", "context": "Desert wildflowers produce an ephemeral bloom following rare winter downpours, withering within days under scorching desert heat."},
    "back": {"meaning": "Lasting for a very short time; fleeting", "synonyms": ["evanescent", "transient", "fleeting"], "contrast": "Not 'permanent' or 'perennial'", "example": "The fame generated by viral internet content is often ephemeral, fading as rapidly as it arose."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-008",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "lucid", "context": "The professor's lucid explanation of quantum entanglement made a notoriously opaque concept accessible to first-year students."},
    "back": {"meaning": "Expressed clearly; easy to understand; characterized by clear perception", "synonyms": ["pellucid", "articulate", "coherent"], "contrast": "Not 'obscure' or 'convoluted'", "example": "A lucid scientific paper presents methodology and conclusions without unnecessary jargon."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-009",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "anachronism", "context": "The depiction of a mechanical clock tower in an ancient Roman marketplace was a glaring historical anachronism."},
    "back": {"meaning": "A thing belonging or appropriate to a period other than that in which it exists", "synonyms": ["chronological error", "incongruity"], "contrast": "Not 'historically authentic'", "example": "Treating 17th-century texts through modern political frameworks risks committing anachronism."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-010",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "ubiquitous", "context": "In modern urban environments, smartphones have become ubiquitous, altering how humans navigate spatial and social environments."},
    "back": {"meaning": "Present, appearing, or found everywhere", "synonyms": ["omnipresent", "pervasive", "universal"], "contrast": "Not 'rare' or 'localized'", "example": "Microplastics are now ubiquitous in ocean ecosystems, detected from Arctic ice to deep oceanic trenches."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-011",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "specious", "context": "The politician's argument sounded persuasive on television, but a closer examination revealed its specious logic."},
    "back": {"meaning": "Superficially plausible, but actually wrong or misleading", "synonyms": ["fallacious", "spurious", "sophistic"], "contrast": "Not 'cogent' or 'sound'", "example": "Advertisers frequently use specious health claims that crumble when subjected to clinical peer review."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-012",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "prosaic", "context": "While tourists envisioned an adventurous life of maritime exploration, the daily routine of a merchant sailor was largely prosaic and repetitive."},
    "back": {"meaning": "Commonplace or dull; lacking poetic beauty or imagination", "synonyms": ["pedestrian", "mundane", "workaday"], "contrast": "Not 'extraordinary' or 'sublime'", "example": "Scientific breakthroughs often emerge from months of prosaic laboratory cataloging."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-013",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "sycophant", "context": "Surrounded by sycophants who praised his every decree, the monarch became increasingly detached from public discontent."},
    "back": {"meaning": "A person who acts obsequiously toward someone important in order to gain advantage", "synonyms": ["flatterer", "toady", "fawner"], "contrast": "Not 'independent critic'", "example": "A wise leader values candid advisors over flattering sycophants."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-014",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "intractable", "context": "The conflict between municipal developers and environmental conservationists appeared intractable after months of deadlock."},
    "back": {"meaning": "Hard to control or deal with; stubborn or unmanageable", "synonyms": ["unyielding", "obstinate", "insoluble"], "contrast": "Not 'malleable' or 'tractable'", "example": "Chronic poverty remains an intractable social challenge requiring systemic structural reform."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  },
  {
    "card_id": "FC-DH-015",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "eschew", "context": "The minimalist architect chose to eschew decorative flourishes in favor of clean lines and raw concrete surfaces."},
    "back": {"meaning": "Deliberately avoid using; abstain from", "synonyms": ["forgo", "shun", "renounce"], "contrast": "Not 'embrace' or 'adopt'", "example": "Ethical researchers eschew conflicts of interest by refusing corporate sponsorship."},
    "skill": "Words in Context",
    "source": "Direct Hits Core Vocabulary"
  }
]

# 2. 50 Crucial Secondary Meaning Words from SAT Power Vocab
secondary_meanings_cards = [
  {
    "card_id": "FC-SEC-001",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "table (verb)", "context": "Due to time constraints, the legislative committee voted to table the environmental amendment until the next legislative session."},
    "back": {"meaning": "To postpone consideration of a topic or proposal indefinitely or until later", "primary_meaning": "A piece of furniture with a flat top and legs", "sat_trap": "Students assume 'table' means to present or discuss; in American parliamentary English, it means to shelve or postpone.", "example": "The board decided to table the budget vote until audit figures were verified."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-002",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "compromise (verb)", "context": "A single cracked seal compromised the submarine's hull integrity, forcing an immediate ascent."},
    "back": {"meaning": "To weaken, undermine, or expose to danger/risk", "primary_meaning": "An agreement reached by mutual concession", "sat_trap": "Assuming it means reaching an amicable agreement; on the SAT it often means 'to damage or endanger'.", "example": "Chemotherapy can compromise the patient's immune system."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-003",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "qualify (verb)", "context": "The climatologist qualified her prediction, stating that rising sea levels would accelerate only if polar ice shelf collapse continued at current rates."},
    "back": {"meaning": "To limit, moderate, or add conditions/exceptions to a statement", "primary_meaning": "To meet the requirements for a job or contest", "sat_trap": "Assuming it means passing a test; on the SAT it almost always means 'to state with qualifications or limitations'.", "example": "The author qualified his endorsement by noting several experimental design flaws."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-004",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "patent (adjective)", "context": "The defendant's claim of ignorance was a patent falsehood, disproved by dozens of timestamped emails."},
    "back": {"meaning": "Easily recognizable; obvious, blatant, or evident", "primary_meaning": "A government license conferring an exclusive right to an invention", "sat_trap": "Interpreting it as an intellectual property document rather than 'glaringly obvious'.", "example": "The judge dismissed the lawsuit, noting the plaintiff's patent lack of standing."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-005",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "champion (verb)", "context": "Throughout her career, the senator championed legislation to expand public access to high-speed broadband."},
    "back": {"meaning": "To support, defend, or fight for a cause or principle vigorously", "primary_meaning": "A person who has defeated all rivals in a competition", "sat_trap": "Assuming it is a noun meaning winner; as a verb it means 'to advocate for'.", "example": "Rachel Carson championed the modern environmental movement through her landmark book Silent Spring."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-006",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "plastic (adjective)", "context": "During early childhood, neural architecture is remarkably plastic, adapting readily to sensory input and environmental stimuli."},
    "back": {"meaning": "Easily shaped or molded; flexible, adaptable, or malleable", "primary_meaning": "Synthetic polymer material used for bottles and packaging", "sat_trap": "Assuming it means fake or synthetic; in biology/psychology it means 'capable of being deformed or reshaped'.", "example": "Neuroplasticity refers to the brain's plastic capacity to reorganize synaptic connections."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-007",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "currency (noun)", "context": "The theory of continental drift gained widespread currency among geologists only after seafloor spreading was documented in the 1960s."},
    "back": {"meaning": "General acceptance, prevalence, or widespread circulation of an idea", "primary_meaning": "A system of money in common use", "sat_trap": "Assuming it refers to dollars or coins; here it refers to an idea being widely accepted.", "example": "The concept of emotional intelligence has gained immense currency in modern corporate management."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-008",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "pedestrian (adjective)", "context": "Critics dismissed the novel's pedestrian plot, noting that its predictable twists offered nothing original to the mystery genre."},
    "back": {"meaning": "Lacking inspiration or excitement; dull, ordinary, or commonplace", "primary_meaning": "A person walking along a road", "sat_trap": "Assuming it refers to walking; as an adjective it means 'prosaic, unimaginative, or mediocre'.", "example": "Despite its stellar cast, the movie was hampered by pedestrian dialogue."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-009",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "intimate (verb)", "context": "Although the diplomat did not make an explicit threat, his measured tone intimated that economic sanctions were imminent."},
    "back": {"meaning": "To state or suggest indirectly; to hint at", "primary_meaning": "Closely acquainted; familiar, private", "sat_trap": "Pronounced IN-tuh-mayt; means 'to imply or insinuate', not 'close/cozy'.", "example": "The CEO intimated that layoffs would be necessary if third-quarter revenues fell short."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-010",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "affect (verb)", "context": "To blend in with the aristocratic court, the merchant affected an elaborate, formal accent that fooled no one."},
    "back": {"meaning": "To pretend to feel or possess; to put on a false appearance of", "primary_meaning": "To have an effect on; make a difference to", "sat_trap": "Assuming it means 'to influence'; here it means 'to feign or pretend'.", "example": "He affected an air of indifference, though he was secretly overjoyed by the praise."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-011",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "appropriate (verb)", "context": "The revolutionary government appropriated private estates and converted them into collective agricultural communes."},
    "back": {"meaning": "To take possession of something, often without permission or legally by authority", "primary_meaning": "Suitable or proper in the circumstances (adjective)", "sat_trap": "Pronounced uh-PRO-pree-ayt (verb); means 'to seize or confiscate', not 'fitting/proper'.", "example": "Congress appropriated $50 million for emergency flood relief."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-012",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "flag (verb)", "context": "As the marathon entered its twentieth mile under midday heat, the runner's endurance began to flag noticeably."},
    "back": {"meaning": "To become tired, weaker, or less enthusiastic; to decline", "primary_meaning": "A piece of cloth with a design used as a national symbol", "sat_trap": "Assuming it refers to a banner or marking something; here it means 'to droop or weaken'.", "example": "Student attention flagged during the three-hour lecture on agricultural tariffs."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-013",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "temper (verb)", "context": "The senior diplomat urged the prime minister to temper his fiery rhetoric with calls for bilateral de-escalation."},
    "back": {"meaning": "To act as a neutralizing or moderating counterforce; to soften or dilute", "primary_meaning": "A person's state of mind seen in terms of being angry or calm", "sat_trap": "Assuming it refers to anger/rage; as a verb it means 'to moderate or balance'.", "example": "Experience had tempered his youthful idealism with pragmatic caution."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-014",
    "type": "vocabulary",
    "difficulty": 3,
    "front": {"word": "check (verb)", "context": "Predatory ladybugs were introduced into the citrus orchards to check the exponential growth of aphid populations."},
    "back": {"meaning": "To stop or slow the progress of something; to curb or restrain", "primary_meaning": "To examine the accuracy or condition of something", "sat_trap": "Assuming it means verifying or inspecting; in academic texts it often means 'to restrain or halt'.", "example": "The constitutional system of checks and balances was designed to check executive overreach."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  },
  {
    "card_id": "FC-SEC-015",
    "type": "vocabulary",
    "difficulty": 4,
    "front": {"word": "reservation (noun)", "context": "While the faculty committee supported the tenure application in principle, several members expressed serious reservations about his teaching evaluations."},
    "back": {"meaning": "A feeling of doubt or uncertainty about a plan or statement", "primary_meaning": "An arrangement by which accommodations are secured in advance", "sat_trap": "Assuming it refers to hotel booking or Native land; here it means 'doubts or hesitations'.", "example": "She accepted the job offer without reservation."},
    "skill": "Words in Context",
    "source": "SAT Power Vocab (Secondary Meanings)"
  }
]

with open(os.path.join(out_dir, 'vocabulary_direct_hits.json'), 'w', encoding='utf-8') as f:
    json.dump(direct_hits_cards, f, indent=2, ensure_ascii=False)
print(f"Created vocabulary_direct_hits.json: {len(direct_hits_cards)} cards.")

with open(os.path.join(out_dir, 'vocabulary_secondary_meanings.json'), 'w', encoding='utf-8') as f:
    json.dump(secondary_meanings_cards, f, indent=2, ensure_ascii=False)
print(f"Created vocabulary_secondary_meanings.json: {len(secondary_meanings_cards)} cards.")
